# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='close',
            field=models.FloatField(help_text='closing price quoted', verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(help_text='Date Mentioned', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='high',
            field=models.FloatField(help_text='High price quoted', verbose_name='High Price'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='low',
            field=models.FloatField(help_text='low price quoted', verbose_name='Low Price'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='open',
            field=models.FloatField(help_text='Opening price quoted', verbose_name='Open Price'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='shares_traded',
            field=models.IntegerField(help_text='shares traded mentioned', verbose_name='Share Traded'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='turnover',
            field=models.FloatField(help_text='turn over quoted', verbose_name='Turn Over (Cr.)'),
        ),
    ]
